<h3 id="promise-的基本结构">Promise 的基本结构</h3>
<pre><code class="language-js">new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    resolve(&quot;FULFILLED&quot;);
  }, 2000);
});</code></pre>
<blockquote>
<p>构造函数 Promise 必须接受一个函数作为参数，我们称该函数为 handle，handle 又包含 resolve 和 reject 两个参数，为两个函数。</p>
</blockquote>
<p><strong>定义 MyPromise</strong></p>
<pre><code class="language-js">const isFunc = (handler) =&gt; typeof handler !== &quot;function&quot;;
class MyPromise {
  constructor(handler) {
    if (!isFunc(handler)) {
      throw new Error(&quot;MyPromise must accept a function as a parameter&quot;);
    }
  }
}</code></pre>
<h3 id="promise-状态和值">Promise 状态和值</h3>
<p><strong>Promise 包含三个状态值</strong></p>
<ul>
<li>Pending(进行中)</li>
<li>Fulfilled(已成功)</li>
<li>Rejected(已失败)</li>
</ul>
<blockquote>
<p>状态只能由 Pending 变为 Fulfilled 或由 Pending 变为 Rejected ，且状态改变之后不会在发生变化，会一直保持这个状态。</p>
</blockquote>
<blockquote>
<p><strong>resolve 和 reject</strong></p>
</blockquote>
<ul>
<li>resolve : 将 Promise 对象的状态从 Pending(进行中) 变为 Fulfilled(已成功)</li>
<li>reject : 将 Promise 对象的状态从 Pending(进行中) 变为 Rejected(已失败)</li>
<li>resolve 和 reject 都可以传入任意类型的值作为实参，表示 Promise 对象成功（Fulfilled）和失败（Rejected）的值</li>
</ul>
<p>MyPromise 添加状态和值，并添加状态改变的执行逻辑：</p>
<pre><code class="language-js">const STATUS = {
  PENDING: &quot;PENDING&quot;,
  FULFILLED: &quot;FULFILLED&quot;,
  REJECTED: &quot;REJECTED&quot;,
};

const isFunction = (handler) =&gt; typeof handler !== &quot;function&quot;;

class MyPromise {
  constructor(handler) {
    if (!isFunction(handler)) {
      throw new Error(&quot;MyPromise must accept a function as a parameter&quot;);
    }
    this._status = STATUS.PENDING;
    try {
      handler(this._resolve, this._reject);
    } catch (e) {
      _reject(e);
    }
  }
  _resolve = (value) =&gt; {
    if (this._status !== STATUS.PENDING) return;
    this._value = value;
    this._status = STATUS.FULFILLED;
  };

  _reject = (e) =&gt; {
    if (this._status !== STATUS.PENDING) return;
    this._value = e;
    this._status = STATUS.REJECTED;
  };
}</code></pre>
<h3 id="promise-的-then-方法">Promise 的 then 方法</h3>
<p>Promise 对象的 then 方法接受两个参数：</p>
<pre><code class="language-js">promise.then(onFulfilled, onRejected);</code></pre>
<p><strong>参数可选</strong>
onFulfilled 和 onRejected 都是可选参数。</p>
<ul>
<li>如果 onFulfilled 或 onRejected 不是函数，其必须被忽略</li>
</ul>
<p><strong>onFulfilled 特性</strong>
如果 onFulfilled 是函数：</p>
<ul>
<li>当 promise 状态变为成功时必须被调用，其第一个参数为 promise 成功状态传入的值(resolve 执行时传入的值）</li>
<li>在 promise 状态改变前其不可被调用</li>
<li>其调用次数不可超过一次</li>
</ul>
<p><strong>onRejected 特性</strong>
如果 onRejected 是函数：</p>
<ul>
<li>当 promise 状态变为失败时必须被调用，其第一个参数为 promise 失败状态传入的值(reject 执行时传入的值）</li>
<li>在 promise 状态改变前其不可被调用</li>
<li>其调用次数不可超过一次</li>
</ul>
<p><strong>多次调用</strong>
then 方法可以被同一个 promise 对象调用多次</p>
<ul>
<li>当 promise 成功状态时，所有 onFulfilled 需按照其注册顺序依次回调</li>
<li>当 promise 失败状态时，所有 onRejected 需按照其注册顺序依次回调</li>
</ul>
<p><strong>返回</strong>
then 方法必须返回一个新的 promise 对象</p>
<pre><code class="language-js">promise2 = promise1.then(onFulfilled, onRejected);</code></pre>
<p>因此 promise 支持链式调用</p>
<pre><code class="language-js">promise1.then(onFulfilled1, onRejected1).then(onFulfilled2, onRejected2);</code></pre>
<p>这里涉及到 Promise 的执行规则，包括“值的传递”和“错误捕获”机制：</p>
<p>1、如果 onFulfilled 或者 onRejected 返回一个值 x ，则运行下面的 Promise 解决过程：</p>
<ul>
<li>若 x 不为 Promise，则使 x 直接作为新返回的 Promise 对象的值， 即新的 onFulfilled 或者 onRejected 函数的参数.</li>
<li>若 x 为 Promise，后一个回调函数，就会等待该 Promise 对象(即 x )的状态发生变化，才会被调用，并且新的 Promise 状态和 x 的状态相同。</li>
</ul>
<p>下面的例子用于帮助理解：</p>
<pre><code class="language-js">let promise1 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    resolve();
  }, 1000);
});
promise2 = promise1.then((res) =&gt; {
  // 返回一个普通值
  return &quot;这里返回一个普通值&quot;;
});
promise2.then((res) =&gt; {
  console.log(res); //1 秒后打印出：这里返回一个普通值
});</code></pre>
<pre><code class="language-js">let promise1 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    resolve();
  }, 1000);
});
promise2 = promise1.then((res) =&gt; {
  // 返回一个 Promise 对象
  return new Promise((resolve, reject) =&gt; {
    setTimeout(() =&gt; {
      resolve(&quot;这里返回一个 Promise&quot;);
    }, 2000);
  });
});
promise2.then((res) =&gt; {
  console.log(res); //3 秒后打印出：这里返回一个 Promise
});</code></pre>
<p>2、如果 onFulfilled 或者 onRejected 抛出一个异常 e ，则 promise2 必须变为失败（Rejected），并返回失败的值 e，例如：</p>
<pre><code class="language-js">let promise1 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    resolve(&quot;success&quot;);
  }, 1000);
});
promise2 = promise1.then((res) =&gt; {
  throw new Error(&quot;这里抛出一个异常 e&quot;);
});
promise2.then(
  (res) =&gt; {
    console.log(res);
  },
  (err) =&gt; {
    console.log(err); //1 秒后打印出：这里抛出一个异常 e
  }
);</code></pre>
<p>3、如果 onFulfilled 不是函数且 promise1 状态为成功（Fulfilled）， promise2 必须变为成功（Fulfilled）并返回 promise1 成功的值，例如：</p>
<pre><code class="language-js">let promise1 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    resolve(&quot;success&quot;);
  }, 1000);
});
promise2 = promise1.then(&quot;这里的 onFulfilled 本来是一个函数，但现在不是&quot;);
promise2.then(
  (res) =&gt; {
    console.log(res); // 1 秒后打印出：success
  },
  (err) =&gt; {
    console.log(err);
  }
);</code></pre>
<p>4、如果 onRejected 不是函数且 promise1 状态为失败（Rejected），promise2 必须变为失败（Rejected） 并返回 promise1 失败的值，例如：</p>
<pre><code class="language-js">let promise1 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    reject(&quot;fail&quot;);
  }, 1000);
});
promise2 = promise1.then(
  (res) =&gt; res,
  &quot;这里的 onRejected 本来是一个函数，但现在不是&quot;
);
promise2.then(
  (res) =&gt; {
    console.log(res);
  },
  (err) =&gt; {
    console.log(err); // 1 秒后打印出：fail
  }
);</code></pre>
<p>根据上面的规则，我们来为 完善 MyPromise</p>
<p>修改 constructor : 增加执行队列</p>
<p>由于 then 方法支持多次调用(同一个 promise 多次调用 then 方法)，我们可以维护两个数组，将每次 then 方法注册时的回调函数添加到数组中，等待执行</p>
<pre><code class="language-js">const isFunction = (handler) =&gt; typeof handler === &quot;function&quot;;
  constructor(handler) {
    if (!isFunction(handler)) {
      throw new Error(&quot;MyPromise must accept a function as a parameter&quot;);
    }
    this._status = STATUS.PENDING;
    this._fulfilledQueue = [];
    this._rejectedQueue = [];
    try {
      handler(this._resolve, this._reject);
    } catch (e) {
      this._reject(e);
    }
  }</code></pre>
<p>添加 then 方法</p>
<p>首先，then 返回一个新的 Promise 对象，并且需要将回调函数加入到执行队列中</p>
<pre><code class="language-js">then = (onFulfilled, onRejected) =&gt; {
  const { _status, _value } = this;
  return new MyPromise((onFulfilledNext, onRejectedNext) =&gt; {
    switch (_status) {
      case STATUS.PENDING:
        this._fulfilledQueue.push(onFulfilled);
        this._rejectedQueue.push(onRejected);
        break;
      case STATUS.FULFILLED:
        onFulfilled(_value);
        break;
      case STATUS.REJECTED:
        onRejected(_value);
        break;
    }
  });
};</code></pre>
<p>根据上文中 then 方法的规则，我们知道返回的新的 Promise 对象的状态依赖于当前 then 方法回调函数执行的情况以及返回值，例如 then 的参数是否为一个函数、回调函数执行是否出错、返回值是否为 Promise 对象。
我们来进一步完善 then 方法:</p>
<pre><code class="language-js">then = (onFulfilled, onRejected) =&gt; {
  const { _status, _value } = this;

  return new MyPromise((onFulfilledNext, onRejectedNext) =&gt; {
    const fulfilled = (value) =&gt; {
      try {
        if (!isFunction(onFulfilled)) {
          onFulfilledNext(value);
        } else {
          let res = onFulfilled(value);
          if (res instanceof MyPromise) {
            res.then(onFulfilledNext, onRejectedNext);
          } else {
            onFulfilledNext(res);
          }
        }
      } catch (e) {
        onRejectedNext(e);
      }
    };

    const rejected = (value) =&gt; {
      try {
        if (!isFunction(onRejected)) {
          onRejectedNext(value);
        } else {
          let res = onRejected(value);
          if (res instanceof MyPromise) {
            res.then(onFulfilledNext, onRejectedNext);
          } else {
            //将返回结果直接作为参数，传入下一个then的回调函数，并立即执行下一个then的回调函数
            onFulfilledNext(res);
          }
        }
      } catch (e) {
        onRejectedNext(e);
      }
    };

    switch (_status) {
      case STATUS.PENDING:
        this._fulfilledQueue.push(fulfilled);
        this._rejectedQueue.push(rejected);
        break;
      case STATUS.FULFILLED:
        fulfilled(_value);
        break;
      case STATUS.REJECTED:
        rejected(_value);
        break;
    }
  });
};</code></pre>
<p>接着修改 _resolve 和 _reject ：依次执行队列中的函数</p>
<p>当 resolve 或 reject 方法执行时，我们依次提取成功或失败任务队列当中的函数开始执行，并清空队列，从而实现 then 方法的多次调用，实现的代码如下：</p>
<pre><code class="language-js">_resolve = (value) =&gt; {
  if (this._status !== STATUS.PENDING) return;

  const run = () =&gt; {
    this._value = value;

    this._status = STATUS.FULFILLED;
    let cb;
    while ((cb = this._fulfilledQueue.shift())) {
      cb(value);
    }
  };
  //根据标准需要异步执行
  setTimeout(run, 0);
};

_reject = (e) =&gt; {
  if (this._status !== STATUS.PENDING) return;

  const run = () =&gt; {
    this._value = e;
    this._status = STATUS.REJECTED;
    let cb;
    while ((cb = this._rejectedQueue.shift())) {
      cb(value);
    }
  };
  //根据标准需要异步执行
  setTimeout(run, 0);
};</code></pre>
<p>上面两个函数在<a href="https://promisesaplus.com/#point-67">标准</a>里是要求异步执行</p>
<blockquote>
<p>In practice, this requirement ensures that onFulfilled and onRejected execute asynchronously, after the event loop turn in which then is called, and with a fresh stack.</p>
</blockquote>
<p>因此加了 setTimeout。</p>
<p>这里还有一种特殊的情况，就是当 resolve 方法传入的参数为一个 Promise 对象时，则该 Promise 对象状态决定当前 Promise 对象的状态。</p>
<pre><code class="language-js">const p1 = new Promise(function(resolve, reject) {
  // ...
});

const p2 = new Promise(function(resolve, reject) {
  // ...
  resolve(p1);
});</code></pre>
<p>上面代码中，p1 和 p2 都是 Promise 的实例，但是 p2 的 resolve 方法将 p1 作为参数，即一个异步操作的结果是返回另一个异步操作。
注意，这时 p1 的状态就会传递给 p2，也就是说，p1 的状态决定了 p2 的状态。如果 p1 的状态是 Pending，那么 p2 的回调函数就会等待 p1 的状态改变；如果 p1 的状态已经是 Fulfilled 或者 Rejected，那么 p2 的回调函数将会立刻执行。
我们来修改_resolve 来支持这样的特性</p>
<pre><code class="language-js">_resolve = (value) =&gt; {
  if (this._status !== STATUS.PENDING) return;

  const run = () =&gt; {
    const runFulfilled = (value) =&gt; {
      let cb;
      while ((cb = this._fulfilledQueue.shift())) {
        cb(value);
      }
    };

    const runRejected = (error) =&gt; {
      let cb;
      while ((cb = this._rejectedQueues.shift())) {
        cb(error);
      }
    };

    /* 如果resolve的参数为Promise对象，则必须等待该Promise对象状态改变后,
        当前Promsie的状态才会改变，且状态取决于参数Promsie对象的状态
      */
    if (value instanceof MyPromise) {
      value.then(
        (value) =&gt; {
          this._value = value;
          this._status = STATUS.FULFILLED;
          runFulfilled(value);
        },
        (err) =&gt; {
          this._value = err;
          this._status = STATUS.REJECTED;
          runRejected(err);
        }
      );
    } else {
      this._value = value;
      this._status = STATUS.FULFILLED;
      runFulfilled(value);
    }
  };

  //根据标准需要异步执行
  setTimeout(run, 0);
};</code></pre>
<p>这样一个 Promise 就基本实现了，现在我们来加一些其它的方法。</p>
<p>catch 方法</p>
<pre><code class="language-js"> catch = (onRejected) =&gt; {
    this.then(null, onRejected);
  };</code></pre>
<p>相当于调用 then 方法, 但只传入 Rejected 状态的回调函数。</p>
<p>finally 方法</p>
<pre><code class="language-js">finally = (fn) =&gt; {
  return this.then(
    function (v) {
      setTimeout(fn);
      return v;
    },
    function (e) {
      setTimeout(fn);
      throw e;
    }
  );
};</code></pre>
<h3 id="静态方法">静态方法</h3>
<ul>
<li><p>resolve</p>
<pre><code class="language-js">static resolve = (value) =&gt; {
  if (value instanceof MyPromise) return value;
  return new Promise((resolve) =&gt; resolve(value));
};</code></pre>
</li>
<li><p>reject</p>
<pre><code class="language-js">  static reject (value) {
    return new MyPromise((resolve ,reject) =&gt; reject(value))
  }</code></pre>
</li>
<li><p>all</p>
<pre><code class="language-js">static all(promises) {
  return new MyPromise((resolve, reject) =&gt; {
    let count = 0;
    let values = [];
    promises.forEach((p, index) =&gt; {
      this.resolve(p)
        .then((v) =&gt; {
          values[index] = v;
          count++;
          if (count === promises.length) resolve(values);
        })
        .catch((e) =&gt; {
          reject(e);
        });
    });
  });
}</code></pre>
</li>
<li><p>race</p>
<pre><code class="language-js">static race(promises) {
  return new MyPromise((resolve, reject) =&gt; {
    promises.forEach((p) =&gt; {
      this.resolve(p)
        .then((v) =&gt; {
          resolve(v);
        })
        .catch((e) =&gt; {
          reject(e);
        });
    });
  });
}</code></pre>
</li>
</ul>
<h3 id="最终实现">最终实现</h3>
<pre><code class="language-js">const STATUS = {
  PENDING: &quot;PENDING&quot;,
  FULFILLED: &quot;FULFILLED&quot;,
  REJECTED: &quot;REJECTED&quot;,
};

const isFunction = (handler) =&gt; typeof handler === &quot;function&quot;;
class MyPromise {
  constructor(handler) {
    if (!isFunction(handler)) {
      throw new Error(&quot;MyPromise must accept a function as a parameter&quot;);
    }

    this._status = STATUS.PENDING;
    this._fulfilledQueue = [];
    this._rejectedQueue = [];
    try {
      handler(this._resolve, this._reject);
    } catch (e) {
      this._reject(e);
    }
  }
  _resolve = (value) =&gt; {
    if (this._status !== STATUS.PENDING) return;

    const run = () =&gt; {
      const runFulfilled = (value) =&gt; {
        let cb;
        while ((cb = this._fulfilledQueue.shift())) {
          cb(value);
        }
      };

      const runRejected = (error) =&gt; {
        let cb;
        while ((cb = this._rejectedQueues.shift())) {
          cb(error);
        }
      };

      /* 如果resolve的参数为Promise对象，则必须等待该Promise对象状态改变后,
        当前Promsie的状态才会改变，且状态取决于参数Promsie对象的状态
      */
      if (value instanceof MyPromise) {
        value.then(
          (value) =&gt; {
            this._value = value;
            this._status = STATUS.FULFILLED;
            runFulfilled(value);
          },
          (err) =&gt; {
            this._value = err;
            this._status = STATUS.REJECTED;
            runRejected(err);
          }
        );
      } else {
        this._value = value;
        this._status = STATUS.FULFILLED;
        runFulfilled(value);
      }
    };

    //根据标准需要异步执行
    setTimeout(run, 0);
  };

  _reject = (e) =&gt; {
    if (this._status !== STATUS.PENDING) return;

    const run = () =&gt; {
      this._value = e;
      this._status = STATUS.REJECTED;
      let cb;
      while ((cb = this._rejectedQueue.shift())) {
        cb(e);
      }
    };
    //根据标准需要异步执行
    setTimeout(run, 0);
  };

  then = (onFulfilled, onRejected) =&gt; {
    const { _status, _value } = this;
    return new MyPromise((onFulfilledNext, onRejectedNext) =&gt; {
      const fulfilled = (value) =&gt; {
        try {
          if (!isFunction(onFulfilled)) {
            onFulfilledNext(value);
          } else {
            let res = onFulfilled(value);
            if (res instanceof MyPromise) {
              res.then(onFulfilledNext, onRejectedNext);
            } else {
              onFulfilledNext(res);
            }
          }
        } catch (e) {
          onRejectedNext(e);
        }
      };

      const rejected = (value) =&gt; {
        try {
          if (!isFunction(onRejected)) {
            onRejectedNext(value);
          } else {
            let res = onRejected(value);
            if (res instanceof MyPromise) {
              res.then(onFulfilledNext, onRejectedNext);
            } else {
              //将返回结果直接作为参数，传入下一个then的回调函数，并立即执行下一个then的回调函数
              onFulfilledNext(res);
            }
          }
        } catch (e) {
          onRejectedNext(e);
        }
      };

      switch (_status) {
        case STATUS.PENDING:
          this._fulfilledQueue.push(fulfilled);
          this._rejectedQueue.push(rejected);
          break;
        case STATUS.FULFILLED:
          fulfilled(_value);
          break;
        case STATUS.REJECTED:
          rejected(_value);
          break;
      }
    });
  };

  catch = (onRejected) =&gt; {
    this.then(null, onRejected);
  };

  static resolve = (value) =&gt; {
    if (value instanceof MyPromise) return value;
    return new MyPromise((resolve) =&gt; resolve(value));
  };

  static reject(value) {
    return new MyPromise((resolve, reject) =&gt; reject(value));
  }

  static all(promises) {
    return new MyPromise((resolve, reject) =&gt; {
      let count = 0;
      let values = [];
      promises.forEach((p, index) =&gt; {
        this.resolve(p)
          .then((v) =&gt; {
            values[index] = v;
            count++;
            if (count === promises.length) resolve(values);
          })
          .catch((e) =&gt; {
            reject(e);
          });
      });
    });
  }

  static race(promises) {
    return new MyPromise((resolve, reject) =&gt; {
      promises.forEach((p) =&gt; {
        this.resolve(p)
          .then((v) =&gt; {
            resolve(v);
          })
          .catch((e) =&gt; {
            reject(e);
          });
      });
    });
  }

  finally = (fn) =&gt; {
    return this.then(
      function(v) {
        setTimeout(fn);
        return v;
      },
      function(e) {
        setTimeout(fn);
        throw e;
      }
    );
  };
}</code></pre>
<h3 id="错误处理">错误处理</h3>
<ul>
<li><p>异步错误
对于异步错误，Promise 并不能直接 catch 到，需要用 reject。</p>
<pre><code class="language-js">new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    //catch不到
    throw new Error(&quot;error&quot;);
  });
}).catch(() =&gt; {
  console.log(&quot;error&quot;);
});</code></pre>
<p>reject catch</p>
<pre><code class="language-js">new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    //能够catch
    reject(&quot;error&quot;);
  });
}).catch(() =&gt; {
  console.log(&quot;error&quot;);
});</code></pre>
</li>
<li><p>try catch 捕获不到异常
在 Promise 中在执行回调时都用 try catch 包裹起来了，因此错误被内部捕获，并未向上抛出。</p>
<pre><code class="language-js">try {
  new Promise(function(resolve, reject) {
    x;
  }).then((v) =&gt; {
    console.log(v);
  });
} catch (e) {
  console.log(&quot;error&quot;, e);
}
//output: Uncaught (in promise) ReferenceError: x is not defined</code></pre>
</li>
</ul>
<h3 id="总结">总结</h3>
<ul>
<li>promise 构造函数为同步执行，then 方法的回调为异步执行
引用自<a href="https://juejin.im/post/5b83cb5ae51d4538cc3ec354">Promise 实现原理</a></li>
</ul>
